# Generated by Django 3.2.9 on 2021-12-02 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20211202_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantstoworkwithcompanysize',
            name='tool',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wants_to_work_with_company_size', to='tool.tool'),
        ),
        migrations.AlterField(
            model_name='wantstoworkwithcountry',
            name='tool',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wants_to_work_with_country', to='tool.tool'),
        ),
        migrations.AlterField(
            model_name='workedwithcompanysize',
            name='tool',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worked_with_company_size', to='tool.tool'),
        ),
        migrations.AlterField(
            model_name='workedwithcountry',
            name='tool',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worked_with_country', to='tool.tool'),
        ),
    ]
