# Generated by Django 3.2.9 on 2021-12-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20211202_2344'),
        ('user', '0002_auto_20211202_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourited',
            field=models.ManyToManyField(blank=True, to='tool.Tool'),
        ),
    ]
