# Generated by Django 3.2.9 on 2021-12-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50)),
                ('category', models.CharField(default='category', max_length=50)),
                ('image', models.CharField(default='image', max_length=200)),
                ('worked_with', models.IntegerField(default=0)),
                ('worked_with_prof_devs', models.IntegerField(default=0)),
                ('worked_others', models.IntegerField(default=0)),
                ('worked_with_independent', models.IntegerField(default=0)),
                ('worked_with_full_time', models.IntegerField(default=0)),
                ('worked_with_part_time', models.IntegerField(default=0)),
                ('worked_with_unemployed', models.IntegerField(default=0)),
                ('worked_with_student', models.IntegerField(default=0)),
                ('worked_with_prefer_not_to_say', models.IntegerField(default=0)),
                ('worked_with_na', models.IntegerField(default=0)),
                ('wants_to_work_with', models.IntegerField(default=0)),
                ('wants_to_work_with_prof_devs', models.IntegerField(default=0)),
                ('wants_to_work_with_others', models.IntegerField(default=0)),
                ('wants_to_work_with_independent', models.IntegerField(default=0)),
                ('wants_to_work_with_full_time', models.IntegerField(default=0)),
                ('wants_to_work_with_part_time', models.IntegerField(default=0)),
                ('wants_to_work_with_unemployed', models.IntegerField(default=0)),
                ('wants_to_work_with_student', models.IntegerField(default=0)),
                ('wants_to_work_with_prefer_not_to_say', models.IntegerField(default=0)),
                ('wants_to_work_with_na', models.IntegerField(default=0)),
                ('linux_prof_dev', models.IntegerField(default=0)),
                ('mac_os_prof_dev', models.IntegerField(default=0)),
                ('windows_prof_dev', models.IntegerField(default=0)),
                ('linux_others', models.IntegerField(default=0)),
                ('mac_os_others', models.IntegerField(default=0)),
                ('windows_others', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkedWithCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_united_states_of_america', models.IntegerField(default=0)),
                ('_united_kingdom', models.IntegerField(default=0)),
                ('_india', models.IntegerField(default=0)),
                ('_germany', models.IntegerField(default=0)),
                ('_france', models.IntegerField(default=0)),
                ('_canada', models.IntegerField(default=0)),
                ('_brazil', models.IntegerField(default=0)),
                ('_poland', models.IntegerField(default=0)),
                ('_netherlands', models.IntegerField(default=0)),
                ('_italy', models.IntegerField(default=0)),
                ('tool', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worked_with_country', to='tool.tool')),
            ],
        ),
        migrations.CreateModel(
            name='WorkedWithCompanySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_just_me', models.IntegerField(default=0)),
                ('_2_to_9_employees', models.IntegerField(default=0)),
                ('_10_to_19_employees', models.IntegerField(default=0)),
                ('_20_to_99_employees', models.IntegerField(default=0)),
                ('_100_to_499_employees', models.IntegerField(default=0)),
                ('_500_to_999_employees', models.IntegerField(default=0)),
                ('_1000_to_4999_employees', models.IntegerField(default=0)),
                ('_5000_to_9999_employees', models.IntegerField(default=0)),
                ('_10000_or_more_employees', models.IntegerField(default=0)),
                ('tool', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worked_with_company_size', to='tool.tool')),
            ],
        ),
        migrations.CreateModel(
            name='WantsToWorkWithCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_united_states_of_america', models.IntegerField(default=0)),
                ('_united_kingdom', models.IntegerField(default=0)),
                ('_india', models.IntegerField(default=0)),
                ('_germany', models.IntegerField(default=0)),
                ('_france', models.IntegerField(default=0)),
                ('_canada', models.IntegerField(default=0)),
                ('_brazil', models.IntegerField(default=0)),
                ('_poland', models.IntegerField(default=0)),
                ('_netherlands', models.IntegerField(default=0)),
                ('_italy', models.IntegerField(default=0)),
                ('tool', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wants_to_work_with_country', to='tool.tool')),
            ],
        ),
        migrations.CreateModel(
            name='WantsToWorkWithCompanySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_just_me', models.IntegerField(default=0)),
                ('_2_to_9_employees', models.IntegerField(default=0)),
                ('_10_to_19_employees', models.IntegerField(default=0)),
                ('_20_to_99_employees', models.IntegerField(default=0)),
                ('_100_to_499_employees', models.IntegerField(default=0)),
                ('_500_to_999_employees', models.IntegerField(default=0)),
                ('_1000_to_4999_employees', models.IntegerField(default=0)),
                ('_5000_to_9999_employees', models.IntegerField(default=0)),
                ('_10000_or_more_employees', models.IntegerField(default=0)),
                ('tool', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wants_to_work_with_company_size', to='tool.tool')),
            ],
        ),
    ]
