# Generated by Django 3.2.9 on 2021-12-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wantstoworkwithcountry',
            old_name='_brazil',
            new_name='brazil',
        ),
        migrations.RenameField(
            model_name='wantstoworkwithcountry',
            old_name='_canada',
            new_name='canada',
        ),
        migrations.RenameField(
            model_name='wantstoworkwithcountry',
            old_name='_france',
            new_name='france',
        ),
        migrations.RenameField(
            model_name='wantstoworkwithcountry',
            old_name='_germany',
            new_name='germany',
        ),
        migrations.RenameField(
            model_name='wantstoworkwithcountry',
            old_name='_india',
            new_name='india',
        ),
        migrations.RenameField(
            model_name='wantstoworkwithcountry',
            old_name='_italy',
            new_name='italy',
        ),
        migrations.RenameField(
            model_name='wantstoworkwithcountry',
            old_name='_netherlands',
            new_name='netherlands',
        ),
        migrations.RenameField(
            model_name='wantstoworkwithcountry',
            old_name='_poland',
            new_name='poland',
        ),
        migrations.RenameField(
            model_name='wantstoworkwithcountry',
            old_name='_united_kingdom',
            new_name='united_kingdom',
        ),
        migrations.RenameField(
            model_name='wantstoworkwithcountry',
            old_name='_united_states_of_america',
            new_name='united_states_of_america',
        ),
        migrations.RenameField(
            model_name='workedwithcountry',
            old_name='_brazil',
            new_name='brazil',
        ),
        migrations.RenameField(
            model_name='workedwithcountry',
            old_name='_canada',
            new_name='canada',
        ),
        migrations.RenameField(
            model_name='workedwithcountry',
            old_name='_france',
            new_name='france',
        ),
        migrations.RenameField(
            model_name='workedwithcountry',
            old_name='_germany',
            new_name='germany',
        ),
        migrations.RenameField(
            model_name='workedwithcountry',
            old_name='_india',
            new_name='india',
        ),
        migrations.RenameField(
            model_name='workedwithcountry',
            old_name='_italy',
            new_name='italy',
        ),
        migrations.RenameField(
            model_name='workedwithcountry',
            old_name='_netherlands',
            new_name='netherlands',
        ),
        migrations.RenameField(
            model_name='workedwithcountry',
            old_name='_poland',
            new_name='poland',
        ),
        migrations.RenameField(
            model_name='workedwithcountry',
            old_name='_united_kingdom',
            new_name='united_kingdom',
        ),
        migrations.RenameField(
            model_name='workedwithcountry',
            old_name='_united_states_of_america',
            new_name='united_states_of_america',
        ),
    ]
